name: build-macos

permissions:
  contents: write

on:
  push:
    paths:
      - "VERSION"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v6.0.0

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '>=1.25'
        check-latest: true
        cache: false

    - name: Install packages
      run: |
        brew install glfw glew

    - name: Install dependencies
      run: |
        cd src
        go mod download

    - name: Build
      run: |
        cd src
        go build -v -ldflags="-s -w" -o Picocrypt-NG Picocrypt-NG.go
      env:
        CGO_ENABLED: 1

    - name: Package as .app in a .dmg
      run: |
        mv dist/macos/Picocrypt-NG.app.zip .
        unzip -d Picocrypt-NG.app Picocrypt-NG.app.zip
        rm Picocrypt-NG.app.zip
        mv src/Picocrypt-NG Picocrypt-NG.app/Contents/MacOS/Picocrypt-NG
        rm Picocrypt-NG.app/Contents/Resources/icon.icns
        mv dist/macos/iconSmall.icns Picocrypt-NG.app/Contents/Resources/icon.icns
        mkdir out
        cp -R Picocrypt-NG.app out
        hdiutil create Picocrypt-NG.dmg -volname Picocrypt-NG -fs APFS -format UDZO -srcfolder out

    - name: Upload artifacts
      uses: actions/upload-artifact@v5.0.0
      with:
        name: build-macos
        path: |
          Picocrypt-NG.dmg
        if-no-files-found: error
        compression-level: 9

    - name: Get version tag
      run: |
        VERSION=$(cat VERSION)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Generate checksums
      run: |
        HASH=$(shasum -a 256 Picocrypt-NG.dmg | cut -d ' ' -f1)
        echo "CHECKSUM_PICOCRYPT_NG=$HASH" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2.4.2
      with:
        files: |
          Picocrypt-NG.dmg
        tag_name: ${{ env.VERSION }}
        make_latest: true
        append_body: true
        body: |
          **macOS:**
          `sha256(Picocrypt-NG.dmg)  ${{ env.CHECKSUM_PICOCRYPT_NG }}`
